lazy val commonSettings = Seq(
  version := "1.0.0-SNAPSHOT",
  organization := "org.combinators",
  
  scalaVersion := "2.12.13",

  resolvers ++= Seq(
    Resolver.sonatypeRepo("releases"),
    Resolver.typesafeRepo("releases")
  ),

  scalacOptions ++= Seq(
    "-unchecked",
    "-deprecation",
    "-feature",
    "-language:implicitConversions",
    "-Ypartial-unification"
  ),

  libraryDependencies ++= Seq(
    "org.combinators" %% "templating" % "1.1.0",
    "org.scalactic" %% "scalactic" % "3.2.2" % "test",
    "org.scalatest" %% "scalatest" % "3.2.2" % "test"
  ),

  headerLicense := Some(HeaderLicense.Custom(
    """|Websecbench is a suite of web security benchmarks generated by (CL)S.
       |Copyright (C) 2021  Jan Bessai and Malte Mues
       |
       |This program is free software; you can redistribute it and/or
       |modify it under the terms of the GNU General Public License
       |as published by the Free Software Foundation; either version 2
       |of the License, or (at your option) any later version.
       |
       |This program is distributed in the hope that it will be useful,
       |but WITHOUT ANY WARRANTY; without even the implied warranty of
       |MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
       |GNU General Public License for more details.
       |
       |You should have received a copy of the GNU General Public License
       |along with this program; if not, write to the Free Software
       |Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
       |""".stripMargin
	)),
  scapegoatVersion in ThisBuild := "1.4.7",
  scapegoatDisabledInspections := Seq(
    "EmptyInterpolatedString",
    "UnsafeTraversableMethods"
  )
)

lazy val root = (Project(id = "websecbench", base = file(".")))
  .settings(commonSettings: _*)
  .settings(
    moduleName := "websecbench",
    libraryDependencies ++= Seq(
      "org.combinators" %% "cls-scala" % "3.0.0",
      "org.scalameta" %% "scalameta" % "3.4.0",
      "org.scalameta" %% "contrib" % "3.4.0",
      "org.combinators" %% "jgitserv" % "0.0.1",
      "org.typelevel" %% "cats-core" % "2.3.1",
      "org.typelevel" %% "cats-effect" % "2.3.1"
    )

  )

