name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Set up JDK 12
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 12
    - name: compile, run, and test
      run: |
        sbt run && sleep 4m &
        sleep 130s
        cd /tmp
        git clone http://127.0.0.1:9000/benchmark42 benchmark42
        cd /tmp/benchmark42
        sbt compile

