name: Scala CI

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Set up JDK, Scala, and SBT
      uses: olafurpg/setup-scala@v10
      with:
        java-version: adopt@1.15
    - name: compile, run, and test
      run: |
        sbt run
        cd target/benchmarks
        sbt compile

